#include <stdio.h>
#include <Windows.h>

int main()
{
	while (1) {
		printf("\n"); Sleep(1);
		printf("     FORMULA     \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("  #############  \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   Created and   \n"); Sleep(1);
		printf("   directed by   \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("    donnaken15   \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   Wesley Zane   \n"); Sleep(1);
		printf("     Kennedy     \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("     roles:      \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   ['editor',    \n"); Sleep(1);
		printf("   'director',   \n"); Sleep(1);
		printf("   'player',     \n"); Sleep(1);
		printf("   'programmer', \n"); Sleep(1);
		printf("   'charter',    \n"); Sleep(1);
		printf("   'designer']   \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("  -------------  \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("  Original song  \n"); Sleep(1);
		printf("  and copyright  \n"); Sleep(1);
		printf("       by        \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   Aphex Twin    \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   Richard D.    \n"); Sleep(1);
		printf("     James       \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("    (c) 1999     \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("    aphextwin    \n"); Sleep(1);
		printf("    .warp.net    \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   LP-WAP-105    \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("  -------------  \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   Warp Records  \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("     warp.net    \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("  -------------  \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   Programming   \n"); Sleep(1);
		printf("    languages    \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("    ['x86asm',   \n"); Sleep(1);
		printf("    'c++','c#',  \n"); Sleep(1);
		printf("   'gamemaker']  \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("  -------------  \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("     Games:      \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("  ['Guitar Hero' \n"); Sleep(1);
		printf("  ,'Stepmania',  \n"); Sleep(1);
		printf("  'BIT.TRIP']    \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("  -------------  \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("     Editing     \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("    Audacity     \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("    videodev     \n"); Sleep(1);
		printf("    soft.com     \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("  -------------  \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   Visualizer    \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   foobar2000    \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("  -------------  \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("    Loading      \n"); Sleep(1);
		printf("    screens      \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   Source SDK    \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("  -------------  \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("     Title       \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("    Help by      \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("    Xah Lee      \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("      math       \n"); Sleep(1);
		printf("    symbols      \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("    eeemo.net    \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("    modifier     \n"); Sleep(1);
		printf("   characters    \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("    Wikipedia    \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   formula       \n"); Sleep(1);
		printf("   (literally)   \n"); Sleep(1);
		printf("   formatting    \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("  -------------  \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("     Random      \n"); Sleep(1);
		printf("   Characters    \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   HxD Editor    \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("  -------------  \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   YouTube hax   \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("    a lot of     \n"); Sleep(1);
		printf("    patience     \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   Privatized    \n"); Sleep(1);
		printf("   or unlisted   \n"); Sleep(1);
		printf("    uploads      \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   Tor Proxies   \n"); Sleep(1);
		printf("    / Circuits   \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   YouTube Data  \n"); Sleep(1);
		printf("      API v3     \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("  Browser HTTP   \n"); Sleep(1);
		printf("    Requests     \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("  -------------  \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   youtube.com   \n"); Sleep(1);
		printf("   /donnaken15   \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   twitter.com   \n"); Sleep(1);
		printf("   /Wezinator35  \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   donnaken15    \n"); Sleep(1);
		printf("      .co.nf     \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("  -------------  \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf("   THANKS FOR    \n"); Sleep(1);
		printf("    WATCHING     \n"); Sleep(1);
		printf("                 \n"); Sleep(1);
		printf(" XII.XXXI.MMXIX  \n"); Sleep(1);
		printf("  XXIII:LV:XXX   \n"); Sleep(1);
		printf("\n"); Sleep(1);
		printf("\n"); Sleep(1);
		printf("\n"); Sleep(1);
		printf("\n"); Sleep(1);
	}
}