ffplay init.avi -fs -autoexit
ffplay scene01.avi -fs -autoexit
ffplay scene02a.avi -fs -autoexit
ffplay scene02b.avi -fs -autoexit
ffplay scene02c.avi -fs -autoexit
ffplay scene03a.avi -fs -autoexit
ffplay scene03b.avi -fs -autoexit
ffplay scene03c.avi -fs -autoexit
ffplay scene03d.avi -fs -autoexit
ffplay scene03e.avi -fs -autoexit
ffplay scene03f.avi -fs -autoexit
ffplay scene03g.avi -fs -autoexit
ffplay scene03h.avi -fs -autoexit
ffplay scene04a.avi -fs -autoexit
ffplay scene04b.avi -fs -autoexit
ffplay scene04c.avi -fs -autoexit
ffplay scene04d.avi -fs -autoexit
ffplay scene05.avi -fs -autoexit
ffplay scene06a.avi -fs -autoexit
ffplay scene06b.avi -fs -autoexit
ffplay scene06c.avi -fs -autoexit
ffplay scene07a.avi -fs -autoexit
ffplay scene07b.avi -fs -autoexit
ffplay scene08.avi -fs -autoexit
ffplay scene09.avi -fs -autoexit
ffplay scene10.avi -fs -autoexit
ffplay scene11.avi -fs -autoexit
ffplay scene12.avi -fs -autoexit
ffplay scene13a.avi -fs -autoexit
ffplay scene13b.avi -fs -autoexit
ffplay scene14.avi -fs -autoexit
ffplay scene15a.avi -fs -autoexit
ffplay scene15b.avi -fs -autoexit
ffplay scene15c.avi -fs -autoexit
ffplay scene15d.avi -fs -autoexit
ffplay scene16.avi -fs -autoexit
ffplay scene17.avi -fs -autoexit
ffplay scene18.avi -fs -autoexit
ffplay scene19.avi -fs -autoexit
ffplay scene20.avi -fs -autoexit
ffplay scene21.avi -fs -autoexit
ffplay scene22.avi -fs -autoexit
ffplay scene23.avi -fs -autoexit